src/Boards/Board.h, src/DCC/ProgRoutines.cpp, src/DCC/RailCom.cpp, src/WiFiInterface/WiThrottle.cpp
=> Fix shift error

CommandStation-EX.ino, src/CommInterface/DCCEXParser.cpp, src/DCC/DCC.h, src/WiFiInterface/WiThrottle.cpp
=> Int library functions knumlocos

CommandStation-EX.ino, Config.h, src/CommInterface/DCCEXParser.cpp, src/CommInterface/DCCEXParser.h, src/DCC/DCC.h, src/DCC/MainRoutines.cpp, src/WiFiInterface/WiThrottle.cpp, src/WiFiInterface/WiThrottle.h
Also added more commands, fixed direction in WiThrottle, fixed internal function packet generation.
=> Implement function reminders

src/CommInterface/DCCEXParser.cpp
Incorrect format %s used instead of %S
=> <s> rubbish

src/CommInterface/DCCEXParser.cpp, src/DCC/DCC.h, src/DCC/MainRoutines.cpp
+ JMRI response to throttle cmds
=> short cab variable fix

CommandStation-EX.ino, Config.h, src/CommInterface/DCCEXParser.cpp, src/DCC/MainRoutines.cpp, src/WiFiInterface/WiFiInterface.cpp
Brings Wifi interface setup up to Cvreader... Yes its not perfect but its better than what was there.
Fixes some throttle stuff (but more to come)
=> Int library

Timer.cpp
Quick merge will delet on the next push
=> revert of timer.cpp

DCC.cpp
shows the <s> info when starting
=> startup Info on USB

DCCEXParser.cpp, Sensors.cpp, Sensors.h
We should have outputs and sensors with <X> now reporting an error, ```<O>``` reporting "ok" and the ```<Z>```, ```<S>``` and ```<Q>``` commands all working properly.
=> Sensor activate

DCCEXParser.cpp
Giving 128 instead of 1 for active
=> Fix T commands

platformio.ini
Align LCD and OLED libraries with the installed code base.
=> Add LCD and OLED libs

.github/workflows/main.yml, I2CManager.cpp, I2CManager.h, LCD_OLED.h, LiquidCrystal_I2C.cpp, LiquidCrystal_I2C.h, PWMServoDriver.cpp, SSD1306Ascii.cpp, SSD1306Ascii.h, SSD1306init.h
Add new read/write functions to I2CManager class, and modify the LCD, OLED and PWM classes to use them effectively.
=> Add I2C support functions

EthernetInterface.cpp
Implement PaulS's change to delay in a loop to give more time for sensing an Ethernet cable connection
=> Add loop to retry Ethernet cable connection

IODevice.cpp, IODevice.h, IO_AnalogueInputs.h, platformio.ini
Add new readAnalogue() function and support for arduino analogue input pins and ADS111x I2C Analogue input modules.
=> Ex rail neil analogue inputs

DCC.cpp, DCC.h, DCCEXParser.cpp, DCCWaveform.cpp
Merge updates to EX-RAIL.  Updates Verify/Retry so that initial value of ackManagerByte is restored prior to the retry.  Also provides notification when Read returns the initial value, which is effectively a retry.  Program steps BIV and ITCBV.
=> Ex rail ash

release_notes.md
WiThrottle and JMRI-related items
=> Some duplication removal and rewording

myAutomation.example.h
Use "starting sequence" to describe the initial instructions.
---
Does that make sense? I found the new use of SEQUENCE in the Introduction to EX-RAIL-intro.html helpful - trying to build on that.
=> Remove EXRAIL/ENDEXRAIL from myAutomation.example.h

DCCEXParser.cpp, DCCEXParser.h
Merge from ServoSignal
Callback parameters are now optional on PROG
=> WRITE CV ON PROG <W CV VALUE>

WifiInboundHandler.cpp, WifiInboundHandler.h
Merge wifi fix into copy of 4.1.1 rc1 master for testing.
=> Amuzzing1 mega wifi inbound fixes

EXRAIL2.cpp, EXRAIL2.h, version.h
Typical output now
```
</><* EXRAIL STATUS
flags[2]  RESERVED
Signal[40] RED
Signal[106] GREEN
Signal[108] AMBER *>
```
=> Fix </> command for signals

DCCEXParser.cpp, EXRAIL2MacroReset.h, EXRAILMacros.h, IODevice.h, IO_EXTurntable.h, myEX-Turntable.example.h
Adding EX-Turntable device driver, diagnostic `<D TT ...>`, and EX-RAIL MOVETT() commands to PORTX_HAL.
=> Add ex turntable

Release_Notes/release_notes_v4.1.1.md
Edited Intro and Rearranged EXRAIL Enhancements
=> Realese Document Edit & Enhancements

version.h
Edited & Reformatted
verify then ready for release
=> Verion.h 4.1.1

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation_update.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/support_request.yml, .github/ISSUE_TEMPLATE/to_do.yml, .github/workflows/new-items.yml
Adding GitHub issue templates to help users and team members provide sufficient information when raising GitHub issues, as well as a workflow to have these and pull requests automatically added to the project Kanban.
=> Add templates and project workflow

IO_EXIOExpander.h
Fixed IO_EXIOExpander.h device driver.
=> Debug-ex-io-expander-on-mega

EXRAIL2.cpp
Fixed bug for SIGNAL/SIGNALH so these now operate as expected instead of being inverted.
=> 294-bug-report-ex-rail-signalsignalh-inverted

IODevice.h, IO_EXIOExpander.h, IO_PCA9685_basic.h, IO_Servo.h, version.h
=> Separate-server-from-pca9685

IO_EXIOExpander.h, version.h
Move servo animations from EX-IOExpander driver to EX-IOExpander software.
=> Fix myHal example for EX-IOExpander

IO_EXIOExpander.h, version.h
Implement non-blocking for all I2CManager reads.
=> Non-blocking implemented

IO_EXIOExpander.h, version.h
Complete fixing EX-IOExpander analogue input bug.
=> Fix-analogue-input-bug

IO_RotaryEncoder.h
Update rotary encoder logic, includes sending a new position initiated from elsewhere to update the rotary encoder
=> Rotary-encoder-send-position

I2CManager.cpp, I2CManager.h, I2CManager_NonBlocking.h, I2CManager_STM32.h, defines.h
The native I2C driver for STM32F4xx needs to come into devel for beta testing.
=> Stm32 i2 c pma neil

DCCEXParser.cpp, IODevice.h, IO_EXTurntable.cpp, version.h
Don't broadcast for accessory updates with no movement
Remove value from throttle position info
=> Updated broadcasts

CommandDistributor.cpp, DCCEXParser.cpp, version.h
Change turntable broadcast from i to I due to conflict with server string.
=> Change broadcast

DCCTimerSTM32.cpp, IO_CMRI.cpp, IO_CMRI.h, myHal.cpp_example.txt, mySetup_h_cmri.txt
The new branch
- bring in the files from devel-Ash
- a next step will add the files from stm32-Eth
- then update for settings needed with F439ZI
=> Add CMRI files

DCCTimerSTM32.cpp, EthernetInterface.cpp, EthernetInterface.h, I2CManager_STM32.h, platformio.ini, version.h
Started with devel 5.2.14 plus the cmri files
This step brings in the changes for Ethernet on F429ZI/F439ZI
=> stm32-Ethernet 

CommandDistributor.cpp, DCC.cpp, DCC.h, DCCEXParser.cpp, EXRAIL2.cpp, GITHUB_SHA.h, TrackManager.cpp, WiThrottle.cpp, version.h
devel-Ash-temp is a clone of devel 5.2.15
push the updates for testing with F439ZI
=> Update for 5.2.15

I2CManager.cpp, IODevice.h, IO_I2CDFPlayer.h, IO_Template.h
Henkk has added capability to use DFplayer via I2C
=> I2C dfplayer

GITHUB_SHA.h, WifiESP32.cpp, WifiInterface.cpp, version.h
Merge from devel
following merge from I2C dfplayer
=> update for devel 5.2.17

IO_I2CDFPlayer.h
=> I2c dfplayer update

DCCEXParser.cpp, EXRAIL2.cpp, EXRAIL2MacroReset.h, EXRAIL2Parser.cpp, EXRAILMacros.h, EthernetInterface.cpp, GITHUB_SHA.h, I2CManager_STM32.h, IODevice.cpp, IODevice.h, IO_EXIOExpander.h, KeywordHasher.h, version.h
devel-stm32EC is a copy of devel-stm32-CMRI
devel-ash-temp0120 is a copy of devel
attempting to merge with conflicts resolved such that Ethernet is unchanged in devel-stm32EC
=> update devel-stm32EC for recent devel changes
