DCC-EX/CommandStation-EX

- objdump.bat
- src/CommInterface/CommManager.h
- src/DCC/DCC.h
- src/DCC/RailCom.cpp
REmoves compiler warning in doNotPrint.
Removes Railcom proxcessing on a UNO compiler
> UNO memory and Compiler warnings

- src/CommInterface/CommManager.h
- src/WiFiInterface/WiFiInterface.cpp
Looks like compiler warning fix is in a PR that beat mine, but still shorten DIAG strings
> Frightrisk int fixes

- src/CommInterface/DCCEXParser.cpp
WiThrottlse passed commands with '<' prefix to DCCEXParser... 
Could have changed Withrottle... instead but .... whaetever
> Fix Wifi <> language

- DCCEXParser.cpp
- DCCEXParser.h
- GITHUB_SHA.h
Fixes fault in <V> command whereby an invalid number of parameters can leave the ack manager locked.
Adds <R> commadn (no params) to read loco id.
Adds GITHUB_SHA facility (automated git action to follow)
> V fixes, R command and github sha.

- DCCEXParser.cpp
- DCCEXParser.h
Implement <M> and <P> commands for transparent DCC packets compatible with Classic DCC++.
Somethimes used by JMRI for consisting.
> M and P commands

- CommandStation-EX.ino
- DCCEX.h
- DCCEXParser.cpp
- DCCEXParser.h
These hooks do NOT require RMFT code to be present.... but they offer the hooks that RMFT will need when available. This is in preparation for adding train automation scripting capability to DCC-EX. The name "RMFT" will probably change in the future.
> RMFT Hooks

- LCDDisplay.cpp
- LCDDisplay.h
Fix situation where page scrolling (SCROLLMODE 1) can cause a blank screen to be displayed.
Also, allow a builder to configure the maximum message length for LCD/OLED display.  Then if they want to create longer messages for some reason, they can take advantage of the 20 or 21 characters available on an LCD2004 or OLED (at the expense of using more RAM for message buffers).  Messages in the standard build should be maintained at 16 characters which is the default max message length, to ensure compatibility with LCD1602 screens.  This therefore has no impact on current program size or ram usage unless activated.  Also, since the messages are written to the screen one character per loop entry, the maximum loop time will be unaffected.
> Nano every2 tweaks

- CommandStation-EX.ino
- DCCWaveform.cpp
- freeMemory.cpp
- freeMemory.h
Add function to maintain a  minimum value seen of free memory.  Add call to it in DCCWaveform interrupt handler (assumed to be the likely worst case for stack usage).  Report this minimum value in main loop.
> More conservative memory monitoring

- DCC.cpp
- WiThrottle.cpp
- WiThrottle.h
Allows EngineDriver to acquire loco from prog track and drive it away.
Also automatically undoes a < 1 JOIN > if any prog track commands issued.
> ED driveaway

- LCDDisplay.cpp
Prevent loop2 from doing anything when lcdDisplay not set up.  If there's a display configured but not one attached, then the OLED code will set lcdDisplay to null and no display will be configured or used by the loop() function.  However, because of the way the initialisation code works, loop2() is called during initialisation.
> Ensure loop2() doesn't run during initialisation if there's no display.

- Turnouts.cpp
- Turnouts.h
On switching, Turnout code was saving entire EEPROM twice, even if EEPROM save had been turned off with the `<e>` command.
It's now been changed so that, after switching of the Turnout, only the tStatus byte is updated (once), and only if the turnout has previously been saved into EEPROM.  This is more like the code for the Outputs and for the original DCC++, but more resilient.
I've performed the following tests:
1) Cleared EEPROM, created turnout and saved to EEPROM:  `<e> <T 1 0 0> <E>`
2) Reset CS and checked that the turnout has been recreated:  `reset, <T>  (responds <H 1 0 0 0>)`
3) Switch turnout, reset and check that turnout state was updated: `<T 1 1>, reset, <T> (responds <H 1 0 0 1>)`
4) Cleared EEPROM, switch turnout and check: `<e> <T 1 0> <T> (responds <H 1 0 0 0>)`
5) …
> Fix turnout handling of EEPROM

- DCC.cpp
- DCC.h
- DCCWaveform.cpp
- DCCWaveform.h
- version.h
Moved more setup out of the BASELINE loop so its not checked every time while waiting for reset counter.
Added REJOIN diag..
If you have a loco moving on prog and you do <R>, the loco will stop, ack its id, and then move off again as it gets the throttle reminder!
> Fix auto rejoin after prog cmd (needs version n umber!)

- SSD1306Ascii.cpp
- SSD1306init.h
Correct display offset for SH1106.  The SH1106 supports 132 columns but most displays use 128 column OLED, connected to the middle columns 2-129.
> SH1106 OLED Display Offset Fix

- DCCEXParser.cpp
- IODevice.cpp
- IODevice.h
- IO_DCCAccessory.cpp
- IO_ExampleSerial.cpp
- IO_ExampleSerial.h
- IO_GPIOBase.h
- IO_HCSR04.h
- IO_MCP23008.h
- IO_MCP23017.h
- IO_PCA9685.cpp
- IO_PCF8574.h
- Sensors.cpp
- Sensors.h
- Turnouts.cpp
Add new `<D SERVO vpin position profile>` command (profile is optional).
Allow HAL device drivers to be statically created by declaration, as an alternative to calling the create() method.
New HAL HC-SR04 driver.
Add on-change notification for GPIOBase class (and implicitly to its subclasses MCP23017, MCP23008 and PCF8574).
Some restructuring of Turnout class to prevent RMFT compile error in IO_NO_HAL mode (basic HAL).
> Various HAL enhancements.

- DCCEXParser.cpp
- I2CManager_NonBlocking.h
- IODevice.cpp
- LCDDisplay.h
- LiquidCrystal_I2C.cpp
- LiquidCrystal_I2C.h
- Turnouts.cpp
- Turnouts.h
- config.example.h
- mySetup.cpp_example.txt
Various updates including I2C fix; enable pullups on GPIO used as input.
The polarity of the `<a>` command relative to the DCC packet contents is still to be finally decided, so has not been changed in this update.
> Ex rail neil rcn213

- IODevice.cpp
- IODevice.h
- IO_AnalogueInputs.h
- IO_DFPlayer.h
- IO_HCSR04.h
- IO_PCA9685.cpp
- IO_VL53L0X.h
- mySetup.cpp_example.txt
Add support for the following:
* DFPlayer MP3 player device,
* VL53L0X Time-Of-Flight ranging device.
Also, some fixes to HCSR04 ultrasound device and analogue input device.
Remove _isBusy() function from HAL devices, use _read() instead.  Top-level IODevice::isBusy(vpin) is retained.
Update mySetup.cpp_example.txt to include examples of each driver.
> Additional and enhanced HAL drivers

- config.example.h
See:
79763a3 ("SH1106 OLED Display Offset Fix (#169)", 2021-06-10)
97f3450 ("Simplify OLED driver initialisation.", 2021-11-24)
---
Wasn't obvious to me what to set OLED_DRIVER to when I had an OLED display described as 128x64. Here's my attempt to make it clearer.
> Clarify config.h entry for an OLED with a SH1106

- README.md
Removed misleading mention of "folder named CommandStation-EX and its subfolders"
> README.md: removed misleading "folder/subfolders"

- EXRAILMacros.h
- IODevice.h
- IO_TurntableEX.h
Updated IO_TurntableEX.h, IODevice.h, and EXRAILMacros.h to enable sending text commands to Turntable-EX via the MOVETT() command rather than the numbers to help make the desired activity easier to understand when reviewing myAutomation.h.
> Add text activities

- DCCEXParser.cpp
Equivalent to <V cv 0>  uses the verify callback.
> Updated CV read command <R cv>

- EthernetInterface.cpp
- EthernetInterface.h
Instead of keeping a limited loop during Ethernet setup, I propose this change to keep checking the link status until it becomes stable and ethernet link is stable and ip is obtained. 
This makes life easier for debugging and testing, also if for some reason the link takes longer to becomes stable, the initialization process will not kill the ehternet singleton.
> Keep Ethernet singleton "alive" until connection is established.

- IO_EXIOExpander.h
EX-IOExpander digital and anlogue reads are now constantly streamed back in one go to optimise sensor read speeds.
> 31-exio-to-do-optimise-read-speed

- MotorDrivers.h
- version.h
As suggested by @habazut over discord and looking at the Motor Shield schematics, A2 / A3 (which map to GPIO35 and GPIO34 on the Wemos D1 R32) better fit the current sensing purpose rather than GPIO36 and GPIO39
> [ESP32] Use GPIO 35/A2 and 34/A3 for current sensing

- IODevice.cpp
- version.h
Added logic to skip default PCA9685/MCP23017 devices if any addresses or Vpins are already defined by user devices.
> Added disable logic

- WiThrottle.cpp
Fix: turnout state should be 2/4, not T2/T4
> Fix: turnout state should be 2/4, not T2/T4

- IO_EXTurntable.h
- IO_RotaryEncoder.h
- version.h
Update IO_RotaryEncoder.h to ignore sending current position
Update IO_EXTurntable.h to remove forced I2C clock speed and show device offline if EX-Turntable not connected
> RotaryEnoder, EX-Turntable fixes

- EXRAIL2MacroReset.h
- EXRAILMacros.h
- Turntables.cpp
- version.h
Remove I2C address from EXTT_TURNTABLE macro so it will work with a  MUX. Now requires extra HAL macro first.
> Separate-hal-extt-turntable

- CommandDistributor.cpp
- CommandDistributor.h
- DCC.h
- DCCEXParser.cpp
- DCCTimer.h
- DCCTimerGiga.cpp
- I2CManager_Wire.h
- MotorDriver.cpp
- MotorDriver.h
- StringFormatter.cpp
- TrackManager.h
- Wifi_NINA.cpp
- Wifi_NINA.h
- defines.h
just tested with a Loco, and it seems fully working now.
a few changes were needed for WiFi_NINA, that work on the Giga. need to make sure they work on other STM32 hardware, just to make sure the changes are not cross-platform breaking.
Note, the Giga has a uFL antenna connector for an external antenna. there is no onboard antenna, though all new Giga's come with a basic antenna. handy if you want to add a uFL to SMA adapter for an external SMA antenna, in case project is inside a metal enclosure.
> Giga onboard Wifi, and signal updates.

- IO_EXIOExpander.h
- version.h
Update EX-IOExpander to cater for devices with either no analogue pins, or no digital pins.
> Ex-ioexpander-no-analogue-pins-fix

- CommandStation-EX.ino
- config.example.h
- version.h
Add #define STARTUP_DELAY 3000 option so faster uCs can start after peripherals and accessories to improve reliablity.
> Add-startup-delay

- DCCWaveform.cpp
- DCCWaveform.h
- MotorDriver.cpp
- MotorDriver.h
- TrackManager.cpp
- TrackManager.h
Generates RailCom cutout signals on MAIN and PROG track, successfuly tested on Arduino Mega2560 with the standard motorshield and RailComDisplay by Paco.
> RailCom cutout for MAIN and PROG track
